### ISSUE TITLE
"benchmarked" must be a devDependency

### ISSUE THREAD

**Issue by bpasero** [jonschlinkert/regex-cache#2]
This dependency pulls in 1000 files that only seem to be used for your benchmarks?

**Comment by jonschlinkert** [comment]
ha, well your issue has a million hyperboles ;)

> only seem to be used for your benchmarks?

 that's okay though, right? seems like having lots of files for benchmarks or test fixtures is a worthy cause. or is there a fixture drought I wasn't told about?

**Comment by bpasero** [comment]
Not sure what you mean. I installed chokidar and deep down it depends on
your module that drags in 1000 files only used for benchmarks. Besides all
the files, on windows I even end up with filesystem errors because the path
length exceeds 255 characters.
Am 10.04.2015 4:24 vorm. schrieb "Jon Schlinkert" <notifications@github.com

**Comment by jonschlinkert** [comment]
Then it must be an outdated version. I'll look into it.

**Comment by sethkinast** [comment]
+1 for making `benchmarked` a devDependency, and not a dependency.

devDeps are installed by default if you do `npm install regex-cache`, so you'll still get it.

But if someone depends on `regex-cache`, we don't really care about installing `benchmarked`.

We're hitting this issue in https://github.com/linkedin/dustjs/issues/632 due to `chokidar => regex-cache => benchmarked` depchain.

It looks like as of the latest version, it is a devdep though, so that means `chokidar` is depping an outdated version. Over to that repo!

**Comment by jonschlinkert** [comment]
It already is in the current version, but I believe there is a bug that needs to be fixed before we update dependents to use this version. I'll be back from vacation on Thursday and will look into it then

**Comment by sethkinast** [comment]
The depchain is `chokidar => anymatch => micromatch => regex-cache@0.3` but yes, tests for micromatch fail when I try upgrading to 0.4. No real rush.

**Comment by jonschlinkert** [comment]
Thanks for the extra info, much appreciated!

**Comment by mattdesl** [comment]
Heh, this is actually why I opened https://github.com/jonschlinkert/micromatch/issues/21 a few days ago. I'm installing watchify locally on a lot of modules and most of its disk space bloat comes from benchmarked. 

A simple fix would be to checkout an older version of regex-cache, change becnhmarked to a devDep, and then push a patch.

**Comment by mattdesl** [comment]
see [this PR](https://github.com/jonschlinkert/regex-cache/pull/3) if you plan to take that route

**Comment by jonschlinkert** [comment]
Exactly what I was thinking

**Comment by doowb** [comment]
Fixed and published in micromatch 2.1.6

**Comment by sethkinast** [comment]
:+1: fixes our downstream issue, thanks
